"""Reserved compatibility subgraph stored in the same Supabase KG tables.

Canonical ontology nodes remain untouched. Runtime compatibility rows are written
under a derived tenant (``__KG_RUNTIME__::<tenant>``) and namespaced internal
entity/relation types. This keeps the canonical tenant counts/schema clean while
letting old deterministic services consume data whose runtime source is the KG.
"""
from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime, timezone
from typing import Any, Iterable, Protocol

from .config import KGRuntimeConfig


RUNTIME_DATASET_ENTITY = "__RuntimeDataset"
RUNTIME_ROW_ENTITY = "__RuntimeRow"
RUNTIME_CONTAINS_RELATION = "__CONTAINS_ROW"
RUNTIME_ONTOLOGY_VERSION = "runtime-compatibility-v1"


def _now() -> str:
    return datetime.now(timezone.utc).isoformat()


@dataclass(frozen=True)
class RuntimeDataset:
    source_path: str
    columns: tuple[str, ...]
    row_count: int
    content_sha256: str
    dataset_hash: str


class RuntimeGraphStore(Protocol):
    def replace_dataset(
        self,
        *,
        tenant_id: str,
        dataset: RuntimeDataset,
        rows: list[dict[str, str]],
    ) -> None: ...

    def list_datasets(self, *, tenant_id: str) -> list[RuntimeDataset]: ...

    def read_rows(self, *, tenant_id: str, dataset_hash: str) -> list[dict[str, str]]: ...


class SupabaseRuntimeGraphStore:
    def __init__(self, *, client: Any, config: KGRuntimeConfig) -> None:
        self.client = client
        self.config = config
        import os
        self.nodes_table = os.getenv("SUPABASE_GRAPH_NODES_TABLE", "kg_nodes")
        self.relationships_table = os.getenv(
            "SUPABASE_GRAPH_RELATIONSHIPS_TABLE", "kg_relationships"
        )

    @classmethod
    def from_env(cls, config: KGRuntimeConfig | None = None) -> "SupabaseRuntimeGraphStore":
        from auth.supabase_client import get_supabase_admin_client

        cfg = config or KGRuntimeConfig.from_env()
        return cls(client=get_supabase_admin_client(), config=cfg)

    @staticmethod
    def _dataset_graph_id(dataset_hash: str) -> str:
        return f"runtime-dataset:{dataset_hash}"

    @staticmethod
    def _row_prefix(dataset_hash: str) -> str:
        return f"runtime-row:{dataset_hash}:"

    @staticmethod
    def _edge_prefix(dataset_hash: str) -> str:
        return f"runtime-edge:{dataset_hash}:"

    def _delete_existing(self, *, mirror_tenant: str, dataset_hash: str) -> None:
        # Remove edges first for Postgres FK safety. The prefixes are reserved and
        # can never overlap canonical graph IDs generated by the HR graph model.
        self.client.table(self.relationships_table).delete().eq(
            "tenant_id", mirror_tenant
        ).like("graph_id", self._edge_prefix(dataset_hash) + "%").execute()
        self.client.table(self.nodes_table).delete().eq(
            "tenant_id", mirror_tenant
        ).like("graph_id", self._row_prefix(dataset_hash) + "%").execute()

    def replace_dataset(
        self,
        *,
        tenant_id: str,
        dataset: RuntimeDataset,
        rows: list[dict[str, str]],
    ) -> None:
        mirror_tenant = self.config.mirror_tenant_id(tenant_id)
        self._delete_existing(mirror_tenant=mirror_tenant, dataset_hash=dataset.dataset_hash)
        now = _now()
        dataset_graph_id = self._dataset_graph_id(dataset.dataset_hash)
        dataset_row = {
            "tenant_id": mirror_tenant,
            "graph_id": dataset_graph_id,
            "entity_type": RUNTIME_DATASET_ENTITY,
            "ontology_version": RUNTIME_ONTOLOGY_VERSION,
            "properties": {
                "runtimeKind": "dataset",
                "sourcePath": dataset.source_path,
                "columns": list(dataset.columns),
                "rowCount": dataset.row_count,
                "contentSha256": dataset.content_sha256,
                "datasetHash": dataset.dataset_hash,
            },
            "provenance": [{
                "source_system": "legacy_source_bootstrap",
                "source_object": dataset.source_path,
                "source_record_key": dataset.content_sha256,
            }],
            "valid_from": None,
            "valid_to": None,
            "created_at": now,
            "updated_at": now,
        }
        self.client.table(self.nodes_table).upsert(
            dataset_row, on_conflict="tenant_id,graph_id"
        ).execute()

        node_rows: list[dict[str, Any]] = []
        for row_number, row in enumerate(rows, start=1):
            suffix = f"{row_number:09d}"
            row_graph_id = self._row_prefix(dataset.dataset_hash) + suffix
            node_rows.append({
                "tenant_id": mirror_tenant,
                "graph_id": row_graph_id,
                "entity_type": RUNTIME_ROW_ENTITY,
                "ontology_version": RUNTIME_ONTOLOGY_VERSION,
                "properties": {
                    "runtimeKind": "row",
                    "sourcePath": dataset.source_path,
                    "rowNumber": row_number,
                    "datasetHash": dataset.dataset_hash,
                    "rowData": row,
                },
                "provenance": [{
                    "source_system": "legacy_source_bootstrap",
                    "source_object": dataset.source_path,
                    "source_record_key": str(row_number),
                }],
                "valid_from": None,
                "valid_to": None,
                "created_at": now,
                "updated_at": now,
            })

        batch = self.config.batch_size
        for start in range(0, len(node_rows), batch):
            self.client.table(self.nodes_table).upsert(
                node_rows[start : start + batch], on_conflict="tenant_id,graph_id"
            ).execute()

    def _paged_nodes(self, query_builder: Any) -> list[dict[str, Any]]:
        rows: list[dict[str, Any]] = []
        page = max(100, min(self.config.batch_size, 1000))
        start = 0
        while True:
            response = query_builder.range(start, start + page - 1).execute()
            chunk = list(response.data or [])
            rows.extend(chunk)
            if len(chunk) < page:
                break
            start += page
        return rows

    def list_datasets(self, *, tenant_id: str) -> list[RuntimeDataset]:
        mirror_tenant = self.config.mirror_tenant_id(tenant_id)
        query = (
            self.client.table(self.nodes_table)
            .select("graph_id,properties")
            .eq("tenant_id", mirror_tenant)
            .eq("entity_type", RUNTIME_DATASET_ENTITY)
            .order("graph_id")
        )
        rows = self._paged_nodes(query)
        result: list[RuntimeDataset] = []
        for row in rows:
            props = dict(row.get("properties") or {})
            result.append(RuntimeDataset(
                source_path=str(props.get("sourcePath") or ""),
                columns=tuple(str(item) for item in (props.get("columns") or [])),
                row_count=int(props.get("rowCount") or 0),
                content_sha256=str(props.get("contentSha256") or ""),
                dataset_hash=str(props.get("datasetHash") or ""),
            ))
        return [item for item in result if item.source_path and item.dataset_hash]

    def read_rows(self, *, tenant_id: str, dataset_hash: str) -> list[dict[str, str]]:
        mirror_tenant = self.config.mirror_tenant_id(tenant_id)
        query = (
            self.client.table(self.nodes_table)
            .select("graph_id,properties")
            .eq("tenant_id", mirror_tenant)
            .eq("entity_type", RUNTIME_ROW_ENTITY)
            .like("graph_id", self._row_prefix(dataset_hash) + "%")
            .order("graph_id")
        )
        rows = self._paged_nodes(query)
        result: list[dict[str, str]] = []
        for row in rows:
            props = dict(row.get("properties") or {})
            raw = props.get("rowData") or {}
            if isinstance(raw, dict):
                result.append({str(k): "" if v is None else str(v) for k, v in raw.items()})
        return result


class MemoryRuntimeGraphStore:
    """Small deterministic store used by tests; mirrors the public store contract."""

    def __init__(self) -> None:
        self.datasets: dict[tuple[str, str], RuntimeDataset] = {}
        self.rows: dict[tuple[str, str], list[dict[str, str]]] = {}

    def replace_dataset(self, *, tenant_id: str, dataset: RuntimeDataset, rows: list[dict[str, str]]) -> None:
        self.datasets[(tenant_id, dataset.dataset_hash)] = dataset
        self.rows[(tenant_id, dataset.dataset_hash)] = [dict(row) for row in rows]

    def list_datasets(self, *, tenant_id: str) -> list[RuntimeDataset]:
        return sorted(
            [dataset for (tid, _), dataset in self.datasets.items() if tid == tenant_id],
            key=lambda item: item.source_path,
        )

    def read_rows(self, *, tenant_id: str, dataset_hash: str) -> list[dict[str, str]]:
        return [dict(row) for row in self.rows.get((tenant_id, dataset_hash), [])]
