import os
import pandas as pd


OUTPUT="tables.sql"

open(OUTPUT,"w").close()


for file in os.listdir("../Data"):

    if file.endswith(".csv"):

        table=file.replace(".csv","").lower().replace(" ","_")


        df=pd.read_csv(
            "../Data/"+file,
            nrows=5
        )


        cols=[]

        for c in df.columns:

            cols.append(
                f'"{c}" text'
            )


        sql=f"""
CREATE TABLE IF NOT EXISTS "{table}"(
id bigint generated by default as identity primary key,
{",".join(cols)}
);

"""


        with open(
            OUTPUT,
            "a"
        ) as f:

            f.write(sql)


print("DONE")
